### ISSUE TITLE
Text generated favicon not vertically centered

### ISSUE THREAD

**Issue by benhammondmusic** [johnsorrentino/favicon.js#3]
On Brave (Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64) on MacOS, the generated text icon is vertically aligned to the top rather than centered and there doesn't seem to be an adjustment option. 

![image](https://user-images.githubusercontent.com/41567007/112763697-c23ae880-8fc2-11eb-82e3-89c166ac11a5.png)

**Comment by benhammondmusic** [comment]
Answered from Twitter:

Hey Ben, this is an issue with Brave's fingerprinting protection feature. The vertical centering is dependent on HTML canvas .getImageData() which Brave blocks. A quick workaround is to temporarily disable fingerprinting detection or download with another browser.

**Comment by johnsorrentino** [comment]
Resolved by https://github.com/johnsorrentino/center.js/pull/2
