### ISSUE TITLE
Latest commit has overridden core features

### ISSUE THREAD

**Issue by luismiddleton** [johnsorrentino/favicon.js#9]
@johnsorrentino 

Looks like the [latest commit](https://github.com/johnsorrentino/favicon.js/commit/2bbc5f2bb3f0ef659e05c1e715624d64296e1205) has accidentally overridden the bulk of the library's core functionality.

Confirming this was done in error?

**Comment by johnsorrentino** [comment]
@luismiddleton 🤦 I pushed to the wrong repo. I will fix soon. Thank you for the heads up.

**Comment by claudio-salvio** [comment]
Hi @johnsorrentino 

Can you fix the repository?
It's a pity that it was broken by a wrong push.

Kind regards,
Claudio Salvio

**Comment by johnsorrentino** [comment]
Reverted
